export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const PICK_TOP_BOTTOM = 'PICK_TOP_BOTTOM';
export const DELETE_TOP_BOTTOM = 'DELETE_TOP_BOTTOM';
export const UPDATE_TOP_BOTTOM = 'UPDATE_TOP_BOTTOM';
export const CHECKOUT_ORDER = 'CHECKOUT_ORDER';
