export const GET_INGRIDIENTS = 'GET_INGRIDIENTS';
export const PICK_INGRIDIENT = 'PICK_INGRIDIENT';
export const DELETE_INGRIDIENT = 'DELETE_INGRIDIENT';
export const DELETE_TOP_BOTTOM_COUNTER = 'DELETE_TOP_BOTTOM_COUNTER';
